name: video_example
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=1.22.0'
dependencies:
  flutter:
    sdk: flutter
  auto_route: ^3.2.1
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  # play videos
  video_player: ^2.2.7


  # prevent screen from sleeping
  wakelock: ^0.5.6

  # switch orientation
  auto_orientation: ^2.1.0

  # listen to orientation
  native_device_orientation: ^1.0.0
  audio_video_progress_bar: ^0.9.0

  flutter_svg: ^0.23.0+1
  sliding_up_panel: ^2.0.0+1
  google_fonts: ^2.1.0
  mockito: ^5.0.16
  page_transition: ^2.0.4
  flutter_bloc: ^7.3.3
  json_serializable: ^6.1.3
  http: ^0.13.4
  path_provider: ^2.0.8
  mocktail: ^0.2.0
  bloc_test: ^8.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.1.7
  auto_route_generator: ^3.2.1
  
flutter:
  fonts:
    - family: RevxNeue
      fonts:
        - asset: assets/fonts/revx_neue/RevxNeueDemo-Regular.ttf
        - asset: assets/fonts/revx_neue/RevxNeueDemo-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/revx_neue/RevxNeueDemo-Italic.ttf
          style: italic
  uses-material-design: true
  assets:
    - assets/
    - assets/academy_assets/
    - assets/thumbnail/
    - assets/json/
    - assets/icons/
    - assets/videos/
    - assets/videos/de/
    - assets/videos/en/
    - assets/videos/homescreen/


    




